"""empty message

Revision ID: 050084cc7f74
Revises: 
Create Date: 2021-04-17 23:08:42.675502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050084cc7f74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('license', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'license')
    op.create_table('house',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('license', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='house_pkey')
    )
    # ### end Alembic commands ###
