"""empty message

Revision ID: b1c090c6d764
Revises: 050084cc7f74
Create Date: 2021-04-17 23:10:05.504408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c090c6d764'
down_revision = '050084cc7f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('license', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='house_pkey')
    )
    # ### end Alembic commands ###
